repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
- repo: local
  hooks:
    - id: unit-tests
      name: python unit tests
      entry: python -m unittest discover
      language: system
      pass_filenames: false
